name: build-python-app
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  push:
    paths:
    - 'lint_test.py'
jobs:
  build-on-push:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "this has been triggered ${{ github.event_name }} event"
      - name: "Checkout repository code"
        uses: actions/checkout@v2
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run lint with pylint
        run: python lint_test.py
  lint2:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository code"
        uses: actions/checkout@v2
      - name: Set up Python 3.9 
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run lint with pylint
        run: python lint_test.py
